import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'
import './globals.css'

export const metadata: Metadata = {
  title: 'React Dynamic Forms — Zod-powered forms with AI superpowers',
  description:
    'Turn a Zod schema, a JSON Schema, or a plain-English prompt into a production-ready React form in seconds. Type-safe. Headless. You own the code.',
  openGraph: {
    title: 'React Dynamic Forms',
    description: 'Zod-powered React forms. Generated by AI.',
    url: 'https://rdf.dev',
    siteName: 'React Dynamic Forms',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'React Dynamic Forms',
    description: 'Zod-powered React forms. Generated by AI.',
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body>{children}</body>
    </html>
  )
}
