import Link from 'next/link'
import { Sparkles, Zap, Shield, Eye, FileText, Feather } from 'lucide-react'

const features = [
  { icon: Zap, title: 'One-liner', body: 'Pass a schema, get a production-ready form.' },
  { icon: Shield, title: 'Type-safe', body: 'Full TypeScript inference from schema to submit.' },
  { icon: Feather, title: 'Tiny', body: 'Sub-15 kb gzipped core. Tree-shakable.' },
  { icon: Eye, title: 'Accessible', body: 'WCAG AA, keyboard-first, ARIA, dark mode.' },
  { icon: FileText, title: 'Hybrid input', body: 'Zod, JSON Schema, or legacy config — take your pick.' },
  { icon: Sparkles, title: 'AI-ready', body: 'Generate schemas from a prompt with one function call.' },
]

export default function Landing() {
  return (
    <main className="mx-auto flex max-w-5xl flex-col gap-24 px-6 py-16">
      <section className="flex flex-col items-center gap-8 text-center">
        <span className="rounded-full border border-border px-3 py-1 text-xs uppercase tracking-wide text-muted-foreground">
          v1.1 — AI launch
        </span>
        <h1 className="text-balance text-5xl font-semibold tracking-tight sm:text-6xl">
          Dynamic React forms, <br />
          powered by Zod. <span className="text-muted-foreground">Generated by AI.</span>
        </h1>
        <p className="max-w-2xl text-balance text-lg text-muted-foreground">
          Turn a Zod schema, a JSON Schema, or a plain-English prompt into a production-ready React
          form in seconds. Fully validated. Fully themeable. You own the code.
        </p>
        <div className="flex flex-wrap items-center justify-center gap-3">
          <Link
            href="/playground"
            className="inline-flex h-11 items-center justify-center rounded-md bg-primary px-6 text-sm font-medium text-primary-foreground hover:bg-primary/90"
          >
            Try the playground →
          </Link>
          <a
            href="https://github.com/rogeroliveira84/react-dynamic-forms"
            className="inline-flex h-11 items-center justify-center rounded-md border border-input px-6 text-sm font-medium hover:bg-muted"
          >
            Star on GitHub ★
          </a>
        </div>
      </section>

      <section className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
        {features.map(({ icon: Icon, title, body }) => (
          <div key={title} className="flex flex-col gap-2 rounded-lg border border-border p-5">
            <Icon className="h-5 w-5 text-primary" />
            <div className="font-medium">{title}</div>
            <p className="text-sm text-muted-foreground">{body}</p>
          </div>
        ))}
      </section>

      <section className="flex flex-col gap-4">
        <h2 className="text-2xl font-semibold tracking-tight">Three ways in</h2>
        <div className="grid grid-cols-1 gap-4 lg:grid-cols-3">
          <CodeCard
            title="Zod"
            code={`import { DynamicForm } from '@rogeroliveira84/react-dynamic-forms-ui'
import '@rogeroliveira84/react-dynamic-forms-ui/styles.css'
import { z } from 'zod'

const schema = z.object({
  email: z.string().email(),
  age: z.number().min(18),
})

<DynamicForm schema={schema} onSubmit={console.log} />`}
          />
          <CodeCard
            title="JSON Schema"
            code={`import { DynamicForm } from '@rogeroliveira84/react-dynamic-forms-ui'

const schema = {
  type: 'object',
  properties: {
    name: { type: 'string', title: 'Name' },
    age:  { type: 'number', minimum: 0 },
  },
  required: ['name'],
}

<DynamicForm schema={schema} onSubmit={console.log} />`}
          />
          <CodeCard
            title="Prompt → Form"
            code={`import { generateSchema } from
  '@rogeroliveira84/react-dynamic-forms-ai'
import { anthropic } from '@ai-sdk/anthropic'

const { internalSchema } = await generateSchema({
  from: 'text',
  prompt: 'A signup form for a SaaS app',
  model: anthropic('claude-sonnet-4-6'),
})

<DynamicForm schema={internalSchema} onSubmit={console.log} />`}
          />
        </div>
      </section>

      <section className="flex flex-col gap-4">
        <h2 className="text-2xl font-semibold tracking-tight">How it compares</h2>
        <div className="overflow-x-auto rounded-lg border border-border">
          <table className="w-full text-sm">
            <thead className="bg-muted/50 text-left">
              <tr>
                <th className="p-3">Feature</th>
                <th className="p-3">RDF</th>
                <th className="p-3">RJSF</th>
                <th className="p-3">JSON Forms</th>
                <th className="p-3">react-hook-form</th>
              </tr>
            </thead>
            <tbody>
              <CompareRow label="Zod schema input" rdf="✅" rjsf="—" jf="—" rhf="✅" />
              <CompareRow label="JSON Schema input" rdf="✅" rjsf="✅" jf="✅" rhf="—" />
              <CompareRow label="shadcn/ui out of the box" rdf="✅" rjsf="—" jf="—" rhf="—" />
              <CompareRow label="AI schema generation" rdf="✅" rjsf="—" jf="—" rhf="—" />
              <CompareRow label="Core bundle (gzip)" rdf="<5 kb" rjsf="~60 kb" jf="~80 kb" rhf="~9 kb" />
            </tbody>
          </table>
        </div>
        <p className="text-xs text-muted-foreground">
          Bundle sizes are approximations from Bundlephobia. All listed libraries are great — this
          table is about fit for Zod-first, AI-assisted workflows.
        </p>
      </section>

      <footer className="flex flex-col items-center gap-2 border-t border-border pt-8 text-center text-sm text-muted-foreground">
        <p>
          MIT licensed · Built by{' '}
          <a className="underline" href="https://github.com/rogeroliveira84">
            Roger Oliveira
          </a>
        </p>
        <div className="flex gap-4">
          <a className="underline" href="https://github.com/rogeroliveira84/react-dynamic-forms">
            GitHub
          </a>
          <Link className="underline" href="/playground">
            Playground
          </Link>
          <a className="underline" href="https://www.npmjs.com/package/@rogeroliveira84/react-dynamic-forms">
            npm
          </a>
        </div>
      </footer>
    </main>
  )
}

function CodeCard({ title, code }: { title: string; code: string }) {
  return (
    <div className="flex flex-col gap-2 rounded-lg border border-border bg-muted/20 p-4">
      <div className="text-sm font-medium">{title}</div>
      <pre className="mono overflow-x-auto text-xs leading-6 text-foreground/90">
        <code>{code}</code>
      </pre>
    </div>
  )
}

function CompareRow({
  label,
  rdf,
  rjsf,
  jf,
  rhf,
}: {
  label: string
  rdf: string
  rjsf: string
  jf: string
  rhf: string
}) {
  return (
    <tr className="border-t border-border">
      <td className="p-3 font-medium">{label}</td>
      <td className="p-3 text-primary">{rdf}</td>
      <td className="p-3 text-muted-foreground">{rjsf}</td>
      <td className="p-3 text-muted-foreground">{jf}</td>
      <td className="p-3 text-muted-foreground">{rhf}</td>
    </tr>
  )
}
